version: '3'
services:
  mysql:
    build:
      dockerfile: ./docker/mysql/Dockerfile
      context: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
